name: OPEnchantUI
main: FPVGAMER\OPEnchantUI\Main
version: '1.0'
api: [3.0.0, 3.9.0, 3.9.3, 4.0.0]
load: POSTWORLD
author: UnknownOre Editor FPVGAMER
permissions:
  op.command: {default: op, description: §eMua Enchant}
